### ISSUE TITLE
UnboundLocalError when using exclude in config since 1.6

### ISSUE THREAD

**Issue by The-Compiler** [jcrocholl/pep8#378] opened 2015-02-08 21:38 UTC
Since pep8 1.6, with this config I get an exception:

```ini
[pep8]
exclude = ez_setup.py
```

Command: `pep8 --config=.config qutebrowser`

Exception:

```
Traceback (most recent call last):
  File "/usr/bin/pep8", line 9, in <module>
    load_entry_point('pep8==1.6.0', 'console_scripts', 'pep8')()
  File "/usr/lib/python3.4/site-packages/pep8.py", line 2051, in _main
    pep8style = StyleGuide(parse_argv=True, config_file=True)
  File "/usr/lib/python3.4/site-packages/pep8.py", line 1744, in __init__
    options, self.paths = process_options(arglist, parse_argv, parser)
  File "/usr/lib/python3.4/site-packages/pep8.py", line 2024, in process_options
    options = read_config(options, args, arglist, parser)
  File "/usr/lib/python3.4/site-packages/pep8.py", line 1983, in read_config
    value = normalize_paths(value, local_dir)
UnboundLocalError: local variable 'local_dir' referenced before assignment
```

**Comment by IanLee1521** [comment] 2015-02-08 21:45
Hi @The-Compiler . This is a duplicate of #377. I literally just pushed version 1.6.1 up to Pypi which fixes this. Let me know if you have any other issues. Sorry for the inconvenience.

**Closed by IanLee1521** 2015-02-08 21:45 UTC

**Comment by The-Compiler** [comment] 2015-02-08 22:18
Whoops, sorry for the noise! To my defense, I did take a look at the issues, but didn't notice github only displays open issues by default. :laughing: 

Thanks for the fix!

**Comment by IanLee1521** [comment] 2015-02-08 22:20
No problem!
